### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by Aniket762** [betaoverflow/project-speakerhub#3]
If you are able to run the application in your localhost. Do write the steps properly on how you were able to. Add links, context and ultimately enhance the documentation. It will be great if you can also describe speaker hub in your words with better synonymous words.

**Comment by ArcaneWizard** [comment]
Hey! I'm new to open source contributing, but since I'm familiar with the Mern stack, I thought I would give this issue a go as my first one. Just wanted to clarify one thing though: by enhancing the documentation, you mean updating the README, correct?

Also, just thought I should check by you if everything is showing up as intended. Here's what I can see with react and node running on localhost (and mongoDB connected):

<img width="1436" alt="Screen Shot 2021-04-27 at 2 51 42 AM" src="https://user-images.githubusercontent.com/42625247/116222805-c3ffe500-a703-11eb-8b85-3764d38d71a3.png">

**Comment by Aniket762** [comment]
Hey @ArcaneWizard yes by updating documentation I meant improving Readme. And yes, it's showing what it should have shown when reactjs and nodejs is running. If you store data in the database you can see the profile cards and corresponding pages. But in another issue, I have mentioned that after adding some extra fields registration form is not working so that's also an issue. You can modify the description of speaker hub and if I missed something on how to initialize the application and spin up in the local host you may add that as well. In contributing guidelines, you can add that work on the issue only when you are assigned like this. Just wanted to create a beginner-friendly issue to promote opensource😃  Hope I am clear. If any doubts feel free to shoot!
